/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.polycar.parser.antlr;

import com.google.inject.Inject;
import fr.unice.polytech.polycar.parser.antlr.internal.InternalAutoLangParser;
import fr.unice.polytech.polycar.services.AutoLangGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class AutoLangParser extends AbstractAntlrParser {

	@Inject
	private AutoLangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAutoLangParser createParser(XtextTokenStream stream) {
		return new InternalAutoLangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Car";
	}

	public AutoLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AutoLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
