/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dsl.ui;

import fr.unice.polytech.dsl.ui.AbstractPolycarUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PolycarUiModule extends AbstractPolycarUiModule {
  public PolycarUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
