/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.polycar.ide;

import fr.unice.polytech.polycar.ide.AbstractAutoLangIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class AutoLangIdeModule extends AbstractAutoLangIdeModule {
}
