/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dsl.ide;

import fr.unice.polytech.dsl.ide.AbstractPolycarIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PolycarIdeModule extends AbstractPolycarIdeModule {
}
