/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.unice.polytech.dsl.PolycarRuntimeModule;
import fr.unice.polytech.dsl.PolycarStandaloneSetup;
import fr.unice.polytech.dsl.ide.PolycarIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class PolycarIdeSetup extends PolycarStandaloneSetup {
  @Override
  public Injector createInjector() {
    PolycarRuntimeModule _polycarRuntimeModule = new PolycarRuntimeModule();
    PolycarIdeModule _polycarIdeModule = new PolycarIdeModule();
    return Guice.createInjector(Modules2.mixin(_polycarRuntimeModule, _polycarIdeModule));
  }
}
