<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="polycar" nsURI="http://fr.unice.polytech.dsl.polycar" nsPrefix="fr.unice.polytech.dsl.polycar">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Car" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rightMotor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="leftMotor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultAction" eType="#//Action"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" upperBound="-1"
        eType="#//Condition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subActions" lowerBound="1"
        upperBound="-1" eType="#//SubAction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActionType">
    <eLiterals name="SPEED"/>
    <eLiterals name="MOTOR_LEFT" value="1"/>
    <eLiterals name="MOTOR_RIGHT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ActionType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentEvent">
    <eOperations name="react"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//EventType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EventType">
    <eLiterals name="TRAFFIC_LIGHT_ON"/>
    <eLiterals name="TRAFFIC_LIGHT_OFF" value="1"/>
    <eLiterals name="FORB_FORWARD" value="2"/>
    <eLiterals name="FORB_LEFT" value="3"/>
    <eLiterals name="FORB_RIGHT" value="4"/>
    <eLiterals name="OFF_ROAD_LEFT" value="5" literal="OFF_ROAD_LEFT"/>
    <eLiterals name="OFF_ROAD_RIGHT" value="6"/>
    <eLiterals name="OBJECT_LEFT" value="7"/>
    <eLiterals name="OBJECT_RIGHT" value="8"/>
    <eLiterals name="OBJECT_MIDDLE" value="9"/>
    <eLiterals name="CAN_GO_LEFT" value="10"/>
    <eLiterals name="CAN_GO_RIGHT" value="11"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="environmentEvents" upperBound="-1"
        eType="#//EnvironmentEvent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//Action"/>
  </eClassifiers>
</ecore:EPackage>
