/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.polycar.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.unice.polytech.polycar.AutoLangRuntimeModule;
import fr.unice.polytech.polycar.AutoLangStandaloneSetup;
import fr.unice.polytech.polycar.ide.AutoLangIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class AutoLangIdeSetup extends AutoLangStandaloneSetup {
  @Override
  public Injector createInjector() {
    AutoLangRuntimeModule _autoLangRuntimeModule = new AutoLangRuntimeModule();
    AutoLangIdeModule _autoLangIdeModule = new AutoLangIdeModule();
    return Guice.createInjector(Modules2.mixin(_autoLangRuntimeModule, _autoLangIdeModule));
  }
}
