/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.polycar;

import fr.unice.polytech.polycar.AbstractAutoLangRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class AutoLangRuntimeModule extends AbstractAutoLangRuntimeModule {
}
