/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.polycar;

import fr.unice.polytech.polycar.AutoLangStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AutoLangStandaloneSetup extends AutoLangStandaloneSetupGenerated {
  public static void doSetup() {
    new AutoLangStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
