/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.polycar.serializer;

import com.google.inject.Inject;
import fr.unice.polytech.polycar.Car;
import fr.unice.polytech.polycar.PolycarPackage;
import fr.unice.polytech.polycar.services.AutoLangGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;

@SuppressWarnings("all")
public class AutoLangSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private AutoLangGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == PolycarPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case PolycarPackage.CAR:
				sequence_Car(context, (Car) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Car returns Car
	 *
	 * Constraint:
	 *     (name=EString speed=EInt?)
	 */
	protected void sequence_Car(ISerializationContext context, Car semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
