/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.polycar.validation;

import fr.unice.polytech.polycar.validation.AbstractAutoLangValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class AutoLangValidator extends AbstractAutoLangValidator {
}
