/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.polycar.ui.contentassist;

import fr.unice.polytech.polycar.ui.contentassist.AbstractAutoLangProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class AutoLangProposalProvider extends AbstractAutoLangProposalProvider {
}
