/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dsl;

import fr.unice.polytech.dsl.PolycarStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PolycarStandaloneSetup extends PolycarStandaloneSetupGenerated {
  public static void doSetup() {
    new PolycarStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
