/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dsl;

import fr.unice.polytech.dsl.AbstractPolycarRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PolycarRuntimeModule extends AbstractPolycarRuntimeModule {
}
