/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.polycar.formatting2;

import com.google.inject.Inject;
import fr.unice.polytech.polycar.services.AutoLangGrammarAccess;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class AutoLangFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private AutoLangGrammarAccess _autoLangGrammarAccess;
  
  @Override
  public void format(final Object obj, final IFormattableDocument document) {
    throw new UnsupportedOperationException("TODO: auto-generated method stub");
  }
}
