/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dsl.parser.antlr;

import com.google.inject.Inject;
import fr.unice.polytech.dsl.parser.antlr.internal.InternalPolycarParser;
import fr.unice.polytech.dsl.services.PolycarGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class PolycarParser extends AbstractAntlrParser {

	@Inject
	private PolycarGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPolycarParser createParser(XtextTokenStream stream) {
		return new InternalPolycarParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Car";
	}

	public PolycarGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PolycarGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
