/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.unice.polytech.dsl.ide.contentassist.antlr.internal.InternalPolycarParser;
import fr.unice.polytech.dsl.services.PolycarGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class PolycarParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(PolycarGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, PolycarGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEventTypeAccess().getAlternatives(), "rule__EventType__Alternatives");
			builder.put(grammarAccess.getActionTypeAccess().getAlternatives(), "rule__ActionType__Alternatives");
			builder.put(grammarAccess.getCarAccess().getGroup(), "rule__Car__Group__0");
			builder.put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
			builder.put(grammarAccess.getEnvironmentEventAccess().getGroup(), "rule__EnvironmentEvent__Group__0");
			builder.put(grammarAccess.getEnvironmentEventAccess().getGroup_1(), "rule__EnvironmentEvent__Group_1__0");
			builder.put(grammarAccess.getSubActionAccess().getGroup(), "rule__SubAction__Group__0");
			builder.put(grammarAccess.getSubActionAccess().getGroup_1(), "rule__SubAction__Group_1__0");
			builder.put(grammarAccess.getSubActionAccess().getGroup_1_4(), "rule__SubAction__Group_1_4__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getCarAccess().getNameAssignment_2(), "rule__Car__NameAssignment_2");
			builder.put(grammarAccess.getCarAccess().getActionsAssignment_5(), "rule__Car__ActionsAssignment_5");
			builder.put(grammarAccess.getCarAccess().getActionsAssignment_6(), "rule__Car__ActionsAssignment_6");
			builder.put(grammarAccess.getCarAccess().getEnvironmentEventsAssignment_9(), "rule__Car__EnvironmentEventsAssignment_9");
			builder.put(grammarAccess.getCarAccess().getEnvironmentEventsAssignment_10(), "rule__Car__EnvironmentEventsAssignment_10");
			builder.put(grammarAccess.getCarAccess().getDefaultActionAssignment_12(), "rule__Car__DefaultActionAssignment_12");
			builder.put(grammarAccess.getActionAccess().getNameAssignment_1(), "rule__Action__NameAssignment_1");
			builder.put(grammarAccess.getActionAccess().getSubActionsAssignment_3(), "rule__Action__SubActionsAssignment_3");
			builder.put(grammarAccess.getActionAccess().getSubActionsAssignment_4(), "rule__Action__SubActionsAssignment_4");
			builder.put(grammarAccess.getEnvironmentEventAccess().getTypeAssignment_1_1(), "rule__EnvironmentEvent__TypeAssignment_1_1");
			builder.put(grammarAccess.getEnvironmentEventAccess().getActionAssignment_1_3(), "rule__EnvironmentEvent__ActionAssignment_1_3");
			builder.put(grammarAccess.getSubActionAccess().getTypeAssignment_1_1(), "rule__SubAction__TypeAssignment_1_1");
			builder.put(grammarAccess.getSubActionAccess().getValueAssignment_1_3(), "rule__SubAction__ValueAssignment_1_3");
			builder.put(grammarAccess.getSubActionAccess().getDurationAssignment_1_4_1(), "rule__SubAction__DurationAssignment_1_4_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private PolycarGrammarAccess grammarAccess;

	@Override
	protected InternalPolycarParser createParser() {
		InternalPolycarParser result = new InternalPolycarParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public PolycarGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PolycarGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
