/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.polycar.ui.tests;

import com.google.inject.Injector;
import fr.unice.polytech.polycar.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class AutoLangUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("fr.unice.polytech.polycar.AutoLang");
	}

}
