/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.polycar.scoping;

import fr.unice.polytech.polycar.scoping.AbstractAutoLangScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class AutoLangScopeProvider extends AbstractAutoLangScopeProvider {
}
