/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.polycar.ui;

import fr.unice.polytech.polycar.ui.AbstractAutoLangUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AutoLangUiModule extends AbstractAutoLangUiModule {
  public AutoLangUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
